### PR TITLE
Add docker compose and update CI omniscidb image

### PR DESCRIPTION
**Pull request by xmnlab**
This PR:

- adds a docker-compose file
- updates CI to use a new omniscidb image with udf support
- it use a temporally image source xmnlab/core-os-cpu:v5.3.0-udf and it should be moved to a properly organization

# MOTIVATION

`docker-compose` is kind of optional as we are handling just 1 service, but it is very helpful to keep docker environment organized and easy to use. For example, it is easier to handle services just using the service name, instead of using the container id.

### CODE REVIEW

**Comment by datapythonista** [comment]
The docker file looks good (I think we'll need our own Dockerfile, so we can edit the config file there), that's why I didn't add it later.

The Makefile doesn't seem very useful, and based on the Ibis experience, where the Makefile there was out of control and very difficult to maintain, I'd prefer to avoid it. For example:
- Set up tests is only run once when setting up the environment, and it's just calling a script. What value does it add to have an alias?
- Same for `pip install -e .`
- The docker container, instead of an alias, maybe better to move the file to the root, so something as simple and standard as `docker-compose up -d` can be used
- I don't think it's common to generate the coverage file locally. Do you generate and check them other than in the CI? If you don't, why an alias to something as simple as `python -m pytest .`?

Of course feel free to define aliases and have a Makefile locally, but I don't think this is useful to be committed, as other developers may be happy with the original commands, which are very straight-forward. And as I said, if we keep adding things to the Makefile, things become out of control, like in Ibis. I spent lots of hours trying to follow aliases of aliases, and trying to find where things are defined, if in Makefile, docker configs, scripts...

Does this make sense?

**Comment by xmnlab** [comment]
> The Makefile doesn't seem very useful, and based on the Ibis experience, where the Makefile there was out of control and very difficult to maintain, I'd prefer to avoid it. 

I don't think it would be the problem here as we don't need to handle all the backends


> Set up tests is only run once when setting up the environment, and it's just calling a script. What value does it add to have an alias?

actually it is not just a alias

```
init-service: start-service
	python ci/setup_tests.py
```

it also depends on `start-service`, so it will start the server first

> Same for pip install -e .

for now, it seems it is just a alias, but my plan is add `pre-commit install` there.
Aso for documentation, we can ask the user to just run this, and we can add everyting we think that would be useful for the develpment there, so the user don't need to worry to much about that.

> The docker container, instead of an alias, maybe better to move the file to the root, so something as simple and standard as docker-compose up -d can be used

maybe, but `make init-service` looks much easier than:

```
docker-compose up -d omniscidb
docker-compose run --rm waiter
python ci/setup_tests.py
```

and I use it very offen

> I don't think it's common to generate the coverage file locally. Do you generate and check them other than in the CI? If you don't, why an alias to something as simple as python -m pytest .

good question, I normally do when there is a coverage test on CI ... as we don't have it now, maybe we don't need that


As I commented, I don't think we will have the same problem as in ibis, and the make commands here are very simple and straightfoward

**Comment by xmnlab** [comment]
@datapythonista I changed this PR to be just about the docker-compose and the omniscidb image name. for now, I am using  a image from `xmnlab/core-os-cpu:v5.3.0-udf`. it just adds the udf support (not the data for tests yet) and I already created an issue to track that. when it is ready we can move it to a proper organization on dockerhub. thanks!

**Comment by xmnlab** [comment]
@datapythonista do you want to review this before the merge is done?

**Comment by datapythonista** [comment]
Any reason why the new docker is under your user and not under the omnisci one? If omnisci is happy with this it's ok for me.

**Comment by xmnlab** [comment]
I don't think it would be a problem for now, an as I commented before, my plan is move that to the omnisci organization soon. but I can double check it now.

**Comment by xmnlab** [comment]
@datapythonista I was checking the log here .. and the setup test task takes 39 seconds. 
I think it doesn't justify for now the creation of a docker image just for omnisci udf or also with the dataset included.

I think the best approach here would be run the docker-compose "manually" inside the step instead of using `services` section. So we can have more flexibility.

If there is no objection I can move forward using this approach.

**Comment by xmnlab** [comment]
in this PR the docker-compose was implemented and used for CI. Also updated to 5.4 that would be useful for UDF implementations.

the current errors on CI now is not related to this PR and it will be treated in a follow up PR. thanks!

**Comment by datapythonista** [comment]
> @datapythonista I was checking the log here .. and the setup test task takes 39 seconds.
> I think it doesn't justify for now the creation of a docker image just for omnisci udf or also with the dataset included.
> 
> I think the best approach here would be run the docker-compose "manually" inside the step instead of using `services` section. So we can have more flexibility.
> 
> If there is no objection I can move forward using this approach.

I do see value in having an OmniSci docker image for Ibis. It makes things simpler, cleaner, the CI is less likely to fail, and it makes testing locally easier. Not that it makes a big difference, and I'm fine using docker compose instead, but I think an image is better.

Either way, I think having the docker in services also is cleaner, and I think would be better to use a health check than the waiter too. If OmniSciDB doesn't have a health check, I'd propose them to add one, makes setting up the CI much easier.

**Pull request merged**
